app/models/cart_item.rb
app/models/genre.rb
app/models/item.rb
app/models/order.rb
app/models/order_detail.rb
app/models/shipping_address.rb

アソシエーション追加

---

app/javascript/packs/application.js
app/javascript/stylesheets/application.scss
app/views/layouts/application.html.erb
config/environments/development.rb
config/webpack/environment.js
db/migrate/20220618041021_create_active_storage_tables.active_storage.rb
db/schema.rb
package.json
yarn.lock

BootstrapとFontAwesomeを追加

---

app/views/public/homes/about.html.erb

Aboutページの作成です

---

app/views/admin/sessions/new.html.erb

管理者ログインの画面です

---

app/controllers/application_controller.rb
app/views/public/registrations/new.html.erb
app/views/public/sessions/new.html.erb

ログイン/新規会員登録機能追加

---

app/controllers/admin/genres_controller.rb
app/views/admin/genres/edit.html.erb
app/views/admin/genres/index.html.erb

ジャンルを追加しました

---

app/controllers/public/items_controller.rb
app/views/public/items/index.html.erb
app/views/public/items/show.html.erb

顧客側商品ページ作成

---

app/controllers/admin/items_controller.rb
app/models/item.rb
app/views/admin/items/edit.html.erb
app/views/admin/items/index.html.erb
app/views/admin/items/show.html.erb
app/views/public/items/show.html.erb

商品のindex、editページ作成

---

app/controllers/public/customers_controller.rb

customerコントローラー名修正

---

app/assets/stylesheets/public/genres.scss
app/controllers/public/genres_controller.rb
app/controllers/public/items_controller.rb
app/helpers/public/genres_helper.rb
app/views/kaminari/_first_page.html.erb
app/views/kaminari/_gap.html.erb
app/views/kaminari/_last_page.html.erb
app/views/kaminari/_next_page.html.erb
app/views/kaminari/_page.html.erb
app/views/kaminari/_paginator.html.erb
app/views/kaminari/_prev_page.html.erb
app/views/public/genres/show.html.erb
app/views/public/items/_sidebar.html.erb
app/views/public/items/index.html.erb
app/views/public/items/show.html.erb
config/routes.rb
test/controllers/public/genres_controller_test.rb

ジャンル検索機能追加

---

app/models/customer.rb
app/views/public/customers/show.html.erb
app/views/public/registrations/new.html.erb
app/views/public/sessions/new.html.erb
app/views/public/shipping_addresses/edit.html.erb
app/views/public/shipping_addresses/index.html.erb

会員側ログイン/新規登録画面/マイページ関連のレイアウト修正

---

app/views/public/customers/unsubscribe.html.erb
app/views/public/registrations/edit.html.erb

会員情報編集/退会画面レイアウト編集

---

app/controllers/admin/order_details_controller.rb
app/controllers/admin/orders_controller.rb
app/models/order.rb
app/models/order_detail.rb
app/views/admin/orders/index.html.erb
app/views/admin/orders/show.html.erb
config/locales/ja.yml
db/migrate/20220623064758_change_making_status_column_to_order_details.rb
db/schema.rb

確認お願いします！
⚠️データベースの中身変えているので、migrateもお願いします！

管理者側のページを追加しました

---

app/controllers/application_controller.rb
app/views/admin/homes/top.html.erb
config/routes.rb

管理者側と会員側でログイン後のページ変更

---

app/controllers/admin/customers_controller.rb
app/controllers/admin/genres_controller.rb
app/controllers/admin/homes_controller.rb
app/controllers/admin/items_controller.rb
app/controllers/admin/order_details_controller.rb
app/controllers/admin/orders_controller.rb
app/controllers/application_controller.rb
app/controllers/public/cart_items_controller.rb
app/controllers/public/customers_controller.rb
app/controllers/public/orders_controller.rb
app/controllers/public/shipping_addresses_controller.rb

会員側と管理者側で権限追加

---

app/views/public/homes/about.html.erb

About画面の作成

---

app/controllers/public/cart_items_controller.rb
app/views/public/cart_items/index.html.erb
app/views/public/orders/confirm.html.erb
app/views/public/orders/show.html.erb

カート機能の修正と合計金額算出方法の訂正

---

app/controllers/public/orders_controller.rb
app/views/public/orders/index.html.erb
app/views/public/orders/show.html.erb

会員側注文履歴詳細画面

---

app/controllers/admin/orders_controller.rb
app/views/admin/orders/index.html.erb
app/views/admin/orders/show.html.erb

管理者側の注文詳細と一覧画面の修正

---

app/controllers/public/cart_items_controller.rb
app/views/public/cart_items/_form.html.erb
app/views/public/cart_items/_subtotal.html.erb
app/views/public/cart_items/_total_payment.html.erb
app/views/public/cart_items/index.html.erb
app/views/public/cart_items/update.js.erb

カート機能の非同期通信の実装

---

app/views/layouts/application.html.erb
app/views/public/cart_items/_total_payment.html.erb
app/views/public/cart_items/update.js.erb

カート機能にアニメーションを追加しました
